apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  namespace: polytasking
  labels:
    app: task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: ericshrader/polytasking_task_service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: password
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: driver

          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: polytasking
spec:
  type: NodePort
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010
