spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-h1wdtqiuos5sex8g.us.auth0.com/.well-known/jwks.json
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://polytasking.crhavnagsawk.us-east-1.rds.amazonaws.com/Polytasking
    username: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
