spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://polytasking.us.auth0.com/.well-known/jwks.json
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
